### PR TITLE
Section 1 - SPA

### PR DESCRIPTION
**Pull request by rickcolosimo**
Remaining MSCD changes to Section 1.

### CODE REVIEW

**Comment by jboehmig** [comment]
Still working through these Rick, thanks for sending.  Just wanted to update you, since we just pushed some other optimizations through in the meantime.

**Comment by rickcolosimo** [comment]
Dear Jason,

```
Thanks -- I've got a lot more markup that I need to upload. I'll be happy once I get them all into the system.
```

Thanks,

Rick

Richard J. Colosimo
rick@thoughtstorm.com
+1.646.701.1080

**Comment by jboehmig** [comment]
Great, please ping me when you are finished so we can take a look all at once.  Thanks Rick!

**Comment by rickcolosimo** [comment]
Hey Jason,

I submitted pull requests for all the docs. I broke them into sections to make it easier.

Thanks,

Rick

Richard J. Colosimo
rick@thoughtstorm.com
m 646-701-1080

**Comment by jboehmig** [comment]
Thanks Rick.  We'll take a look.

**Pull request closed without merging**
